# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Things you Hitherto Could not Find Through a Search Engine 
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Did Google Search bring you here to find the solution to an obscure problem? 
  Then you have a privilege whose absence inspired this blog. 
  I am a happy cookie for having granted you this privilege.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site
github_username:  matthhan

# Build settings
markdown: kramdown
